// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	LicenseMetadataInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(LicenseMetadataInfo) })
}

func (r LicenseMetadataInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.LicenseMetadataPath); err != nil {
		return err
	}

	if err = r.LicenseMetadataDepSet.EncodeInterface(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *LicenseMetadataInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.LicenseMetadataPath = nil
	} else {
		r.LicenseMetadataPath = val2.(Path)
	}

	if err = r.LicenseMetadataDepSet.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	return err
}

var LicenseMetadataInfoGobRegId int16

func (r LicenseMetadataInfo) GetTypeId() int16 {
	return LicenseMetadataInfoGobRegId
}
