// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	licenseSdkMemberTypeGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(licenseSdkMemberType) })
}

func (r licenseSdkMemberType) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.SdkMemberTypeBase.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *licenseSdkMemberType) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.SdkMemberTypeBase.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var licenseSdkMemberTypeGobRegId int16

func (r licenseSdkMemberType) GetTypeId() int16 {
	return licenseSdkMemberTypeGobRegId
}
