// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	LogtagsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(LogtagsInfo) })
}

func (r LogtagsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Logtags == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.Logtags))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Logtags); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Logtags[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *LogtagsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int32
	err = gobtools.DecodeSimple[int32](buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Logtags = make([]Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.Logtags[val4] = nil
			} else {
				r.Logtags[val4] = val6.(Path)
			}
		}
	}

	return err
}

var LogtagsInfoGobRegId int16

func (r LogtagsInfo) GetTypeId() int16 {
	return LogtagsInfoGobRegId
}
