// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	TestModuleInformationGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TestModuleInformation) })
}

func (r TestModuleInformation) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, r.TestOnly); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.TopLevelTarget); err != nil {
		return err
	}
	return err
}

func (r *TestModuleInformation) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeSimple[bool](buf, &r.TestOnly)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.TopLevelTarget)
	if err != nil {
		return err
	}

	return err
}

var TestModuleInformationGobRegId int16

func (r TestModuleInformation) GetTypeId() int16 {
	return TestModuleInformationGobRegId
}
