// Code generated by go run gob_gen.go; DO NOT EDIT.

package cc

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	imageSdkTraitStructGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(imageSdkTraitStruct) })
}

func (r imageSdkTraitStruct) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.SdkMemberTraitBase.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *imageSdkTraitStruct) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.SdkMemberTraitBase.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var imageSdkTraitStructGobRegId int16

func (r imageSdkTraitStruct) GetTypeId() int16 {
	return imageSdkTraitStructGobRegId
}
