// Code generated by go run gob_gen.go; DO NOT EDIT.

package cc

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	librarySdkMemberTypeGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(librarySdkMemberType) })
}

func (r librarySdkMemberType) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.SdkMemberTypeBase.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.prebuiltModuleType); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.noOutputFiles); err != nil {
		return err
	}
	return err
}

func (r *librarySdkMemberType) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.SdkMemberTypeBase.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.prebuiltModuleType)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.noOutputFiles)
	if err != nil {
		return err
	}

	return err
}

var librarySdkMemberTypeGobRegId int16

func (r librarySdkMemberType) GetTypeId() int16 {
	return librarySdkMemberTypeGobRegId
}
