// Code generated by go run gob_gen.go; DO NOT EDIT.

package cc

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	nativeBridgeSdkTraitStructGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(nativeBridgeSdkTraitStruct) })
}

func (r nativeBridgeSdkTraitStruct) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.SdkMemberTraitBase.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *nativeBridgeSdkTraitStruct) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.SdkMemberTraitBase.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var nativeBridgeSdkTraitStructGobRegId int16

func (r nativeBridgeSdkTraitStruct) GetTypeId() int16 {
	return nativeBridgeSdkTraitStructGobRegId
}
